"""
Generate synthetic prior-authorization data for Project 3.

All patients, providers, payers, identifiers, and authorization
records generated by this script are fictional.

Author: Brandon McDermott
"""

import csv
import random
from datetime import datetime, timedelta
from pathlib import Path


# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

RANDOM_SEED = 42
NUMBER_OF_PATIENTS = 50
NUMBER_OF_AUTHORIZATIONS = 200

random.seed(RANDOM_SEED)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = PROJECT_ROOT / "data" / "source"
OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# Utility functions
# ------------------------------------------------------------

def write_csv(filename, fieldnames, rows):
    """Write a list of dictionaries to a CSV file."""

    output_path = OUTPUT_DIRECTORY / filename

    with output_path.open(
        mode="w",
        newline="",
        encoding="utf-8"
    ) as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=fieldnames
        )
        writer.writeheader()
        writer.writerows(rows)

    print(f"Created {filename}: {len(rows)} records")


def format_datetime(value):
    """Convert datetime objects to MySQL-compatible strings."""

    if value is None:
        return ""

    return value.strftime("%Y-%m-%d %H:%M:%S")


def format_date(value):
    """Convert date or datetime objects to ISO date strings."""

    return value.strftime("%Y-%m-%d")


def random_datetime(start, end):
    """Generate a random datetime between two values."""

    total_seconds = int((end - start).total_seconds())
    random_seconds = random.randint(0, total_seconds)

    return start + timedelta(seconds=random_seconds)


# ------------------------------------------------------------
# Patients
# ------------------------------------------------------------

first_names = [
    "Elena", "Marcus", "Sophia", "Daniel", "Maya",
    "Anthony", "Olivia", "Ethan", "Grace", "Julian",
    "Nora", "Samuel", "Leah", "Isaac", "Chloe",
    "Adrian", "Mia", "Gabriel", "Zoe", "Nathan"
]

last_names = [
    "Torres", "Chen", "Williams", "Patel", "Murphy",
    "Johnson", "Rivera", "Kim", "Thompson", "Nguyen",
    "Martinez", "Brown", "Davis", "Wilson", "Anderson",
    "Thomas", "Jackson", "White", "Harris", "Clark"
]

sex_values = ["female", "male", "other", "unknown"]

postal_codes = [
    "07054", "07834", "07866", "07046", "07960",
    "07470", "07950", "07801", "07005", "07928"
]

patients = []

for number in range(1, NUMBER_OF_PATIENTS + 1):
    birth_start = datetime(1945, 1, 1)
    birth_end = datetime(2005, 12, 31)

    birth_date = random_datetime(
        birth_start,
        birth_end
    ).date()

    patient = {
        "patient_id": f"PAT{number:03d}",
        "medical_record_number": f"MRN{100000 + number}",
        "first_name": random.choice(first_names),
        "last_name": random.choice(last_names),
        "birth_date": format_date(birth_date),
        "administrative_sex": random.choices(
            sex_values,
            weights=[48, 48, 2, 2],
            k=1
        )[0],
        "postal_code": random.choice(postal_codes)
    }

    patients.append(patient)


# ------------------------------------------------------------
# Providers
# ------------------------------------------------------------

providers = [
    {
        "provider_id": "PRV001",
        "npi": "1000000001",
        "provider_name": "Maya Chen, MD",
        "specialty": "Orthopedic Surgery",
        "organization_name": "Northstar Medical Group",
        "active": 1
    },
    {
        "provider_id": "PRV002",
        "npi": "1000000002",
        "provider_name": "Daniel Brooks, MD",
        "specialty": "Neurology",
        "organization_name": "Northstar Medical Group",
        "active": 1
    },
    {
        "provider_id": "PRV003",
        "npi": "1000000003",
        "provider_name": "Sophia Patel, DO",
        "specialty": "Primary Care",
        "organization_name": "Northstar Primary Care",
        "active": 1
    },
    {
        "provider_id": "PRV004",
        "npi": "1000000004",
        "provider_name": "Marcus Rivera, MD",
        "specialty": "Cardiology",
        "organization_name": "Northstar Heart Center",
        "active": 1
    },
    {
        "provider_id": "PRV005",
        "npi": "1000000005",
        "provider_name": "Olivia Murphy, MD",
        "specialty": "Rheumatology",
        "organization_name": "Northstar Specialty Care",
        "active": 1
    },
    {
        "provider_id": "PRV006",
        "npi": "1000000006",
        "provider_name": "Ethan Williams, MD",
        "specialty": "Pain Medicine",
        "organization_name": "Northstar Specialty Care",
        "active": 1
    },
    {
        "provider_id": "PRV007",
        "npi": "1000000007",
        "provider_name": "Grace Thompson, MD",
        "specialty": "Oncology",
        "organization_name": "Northstar Cancer Center",
        "active": 1
    },
    {
        "provider_id": "PRV008",
        "npi": "1000000008",
        "provider_name": "Julian Kim, MD",
        "specialty": "Gastroenterology",
        "organization_name": "Northstar Medical Group",
        "active": 1
    },
    {
        "provider_id": "PRV009",
        "npi": "1000000009",
        "provider_name": "Nora Davis, MD",
        "specialty": "Pulmonology",
        "organization_name": "Northstar Specialty Care",
        "active": 1
    },
    {
        "provider_id": "PRV010",
        "npi": "1000000010",
        "provider_name": "Samuel Nguyen, MD",
        "specialty": "Physical Medicine",
        "organization_name": "Northstar Rehabilitation",
        "active": 1
    }
]


# ------------------------------------------------------------
# Payers
# ------------------------------------------------------------

payers = [
    {
        "payer_id": "PAY001",
        "payer_name": "Summit Health Plan",
        "plan_type": "PPO",
        "standard_sla_hours": 72,
        "expedited_sla_hours": 24,
        "active": 1
    },
    {
        "payer_id": "PAY002",
        "payer_name": "HarborCare Insurance",
        "plan_type": "HMO",
        "standard_sla_hours": 96,
        "expedited_sla_hours": 24,
        "active": 1
    },
    {
        "payer_id": "PAY003",
        "payer_name": "Evergreen Benefit Partners",
        "plan_type": "EPO",
        "standard_sla_hours": 72,
        "expedited_sla_hours": 12,
        "active": 1
    },
    {
        "payer_id": "PAY004",
        "payer_name": "Garden State Community Health",
        "plan_type": "Medicaid",
        "standard_sla_hours": 120,
        "expedited_sla_hours": 24,
        "active": 1
    },
    {
        "payer_id": "PAY005",
        "payer_name": "NorthPoint Senior Advantage",
        "plan_type": "Medicare Advantage",
        "standard_sla_hours": 96,
        "expedited_sla_hours": 24,
        "active": 1
    }
]


# ------------------------------------------------------------
# Coverage
# ------------------------------------------------------------

coverages = []

# One active coverage record for every patient.
for number, patient in enumerate(patients, start=1):
    payer = random.choice(payers)

    coverages.append({
        "coverage_id": f"COV{number:03d}",
        "patient_id": patient["patient_id"],
        "payer_id": payer["payer_id"],
        "member_id": f"MBR{100000 + number}",
        "group_number": f"GRP{2000 + number}",
        "coverage_start_date": "2025-01-01",
        "coverage_end_date": "2026-12-31",
        "coverage_status": "active"
    })

# Five historical inactive records demonstrate coverage changes.
for number in range(1, 6):
    coverages.append({
        "coverage_id": f"COV{50 + number:03d}",
        "patient_id": f"PAT{number:03d}",
        "payer_id": payers[(number - 1) % len(payers)]["payer_id"],
        "member_id": f"HIST{100000 + number}",
        "group_number": f"HGRP{3000 + number}",
        "coverage_start_date": "2024-01-01",
        "coverage_end_date": "2024-12-31",
        "coverage_status": "inactive"
    })

active_coverages = [
    coverage
    for coverage in coverages
    if coverage["coverage_status"] == "active"
]


# ------------------------------------------------------------
# Procedures
# ------------------------------------------------------------

procedures = [
    {
        "procedure_id": "PROC001",
        "procedure_code": "72148",
        "procedure_description": "MRI lumbar spine without contrast",
        "service_category": "Diagnostic Imaging",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC002",
        "procedure_code": "70553",
        "procedure_description": "MRI brain with and without contrast",
        "service_category": "Diagnostic Imaging",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC003",
        "procedure_code": "73721",
        "procedure_description": "MRI lower-extremity joint without contrast",
        "service_category": "Diagnostic Imaging",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC004",
        "procedure_code": "71260",
        "procedure_description": "CT chest with contrast",
        "service_category": "Diagnostic Imaging",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC005",
        "procedure_code": "74177",
        "procedure_description": "CT abdomen and pelvis with contrast",
        "service_category": "Diagnostic Imaging",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC006",
        "procedure_code": "93306",
        "procedure_description": "Complete transthoracic echocardiography",
        "service_category": "Cardiology",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC007",
        "procedure_code": "62323",
        "procedure_description": "Lumbar epidural injection",
        "service_category": "Pain Management",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC008",
        "procedure_code": "27447",
        "procedure_description": "Total knee arthroplasty",
        "service_category": "Surgery",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC009",
        "procedure_code": "43239",
        "procedure_description": "Upper gastrointestinal endoscopy with biopsy",
        "service_category": "Gastroenterology",
        "authorization_required": 1
    },
    {
        "procedure_id": "PROC010",
        "procedure_code": "97110",
        "procedure_description": "Therapeutic exercise treatment",
        "service_category": "Rehabilitation",
        "authorization_required": 1
    }
]


# ------------------------------------------------------------
# Diagnoses
# ------------------------------------------------------------

diagnoses = [
    {
        "diagnosis_id": "DX001",
        "diagnosis_code": "M54.50",
        "diagnosis_description": "Low back pain, unspecified",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX002",
        "diagnosis_code": "M25.561",
        "diagnosis_description": "Pain in right knee",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX003",
        "diagnosis_code": "R51.9",
        "diagnosis_description": "Headache, unspecified",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX004",
        "diagnosis_code": "R07.9",
        "diagnosis_description": "Chest pain, unspecified",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX005",
        "diagnosis_code": "R10.9",
        "diagnosis_description": "Abdominal pain, unspecified",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX006",
        "diagnosis_code": "M17.11",
        "diagnosis_description": "Unilateral primary osteoarthritis, right knee",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX007",
        "diagnosis_code": "M54.16",
        "diagnosis_description": "Lumbar radiculopathy",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX008",
        "diagnosis_code": "R06.02",
        "diagnosis_description": "Shortness of breath",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX009",
        "diagnosis_code": "K21.9",
        "diagnosis_description": "Gastro-esophageal reflux disease",
        "code_system": "ICD-10-CM"
    },
    {
        "diagnosis_id": "DX010",
        "diagnosis_code": "M25.512",
        "diagnosis_description": "Pain in left shoulder",
        "code_system": "ICD-10-CM"
    }
]


# ------------------------------------------------------------
# Authorization requests and status history
# ------------------------------------------------------------

final_statuses = (
    ["Approved"] * 80
    + ["Denied"] * 30
    + ["In Review"] * 30
    + ["Submitted"] * 20
    + ["Additional Information Required"] * 20
    + ["Draft"] * 10
    + ["Cancelled"] * 10
)

random.shuffle(final_statuses)

authorization_requests = []
status_history = []

request_start = datetime(2026, 1, 1, 8, 0, 0)
request_end = datetime(2026, 6, 30, 17, 0, 0)

status_event_counter = 1

for number, final_status in enumerate(final_statuses, start=1):
    authorization_id = f"AUTH{number:04d}"

    coverage = random.choice(active_coverages)
    patient_id = coverage["patient_id"]

    provider = random.choice(providers)
    procedure = random.choice(procedures)
    diagnosis = random.choice(diagnoses)

    created_at = random_datetime(request_start, request_end)
    urgency = random.choices(
        ["standard", "expedited"],
        weights=[85, 15],
        k=1
    )[0]

    # Requests with an additional-information step are not
    # complete on their first submission.
    had_rework = False

    if final_status in ("Approved", "Denied", "In Review"):
        had_rework = random.random() < 0.25
    elif final_status == "Additional Information Required":
        had_rework = True

    initial_submission_complete = not had_rework

    status_sequence = ["Draft"]

    if final_status == "Draft":
        submitted_at = None

    elif final_status == "Cancelled":
        if random.random() < 0.5:
            status_sequence.append("Cancelled")
            submitted_at = None
        else:
            status_sequence.extend(["Submitted", "Cancelled"])
            submitted_at = created_at + timedelta(
                hours=random.randint(2, 24)
            )

    else:
        submitted_at = created_at + timedelta(
            hours=random.randint(2, 24)
        )

        status_sequence.append("Submitted")

        if had_rework:
            status_sequence.append(
                "Additional Information Required"
            )

            if final_status != "Additional Information Required":
                status_sequence.append("Submitted")

        if final_status in ("In Review", "Approved", "Denied"):
            status_sequence.append("In Review")

        if final_status in ("Approved", "Denied"):
            status_sequence.append(final_status)

    event_time = created_at
    decision_at = None

    for sequence_number, status in enumerate(status_sequence):
        if sequence_number == 0:
            event_time = created_at
        elif status == "Submitted" and submitted_at is not None:
            if event_time < submitted_at:
                event_time = submitted_at
            else:
                event_time += timedelta(
                    hours=random.randint(4, 24)
                )
        else:
            event_time += timedelta(
                hours=random.randint(4, 36)
            )

        if status in ("Approved", "Denied"):
            decision_at = event_time

        actor_by_status = {
            "Draft": "Authorization Specialist",
            "Submitted": "Authorization Specialist",
            "Additional Information Required": "Payer",
            "In Review": "Payer",
            "Approved": "Payer",
            "Denied": "Payer",
            "Cancelled": "Authorization Specialist"
        }

        action_required = int(
            status == "Additional Information Required"
        )

        status_history.append({
            "status_event_id": f"EVT{status_event_counter:06d}",
            "authorization_id": authorization_id,
            "status": status,
            "status_at": format_datetime(event_time),
            "actor_type": actor_by_status[status],
            "action_required": action_required,
            "event_notes": (
                "Additional clinical documentation requested"
                if status == "Additional Information Required"
                else f"Authorization status changed to {status}"
            )
        })

        status_event_counter += 1

    if final_status == "Additional Information Required":
        documentation_status = "incomplete"
    elif final_status == "Draft":
        documentation_status = "pending-review"
    elif final_status == "Cancelled" and submitted_at is None:
        documentation_status = "pending-review"
    else:
        documentation_status = "complete"

    authorization_number = (
        f"PA-{260000 + number}"
        if final_status == "Approved"
        else ""
    )

    denial_reason = ""

    if final_status == "Denied":
        denial_reason = random.choice([
            "Medical necessity criteria not met",
            "Required clinical documentation incomplete",
            "Requested service not covered by plan",
            "Alternative treatment required before approval",
            "Out-of-network service limitation"
        ])

    requested_service_date = (
        created_at.date()
        + timedelta(days=random.randint(7, 45))
    )

    authorization_requests.append({
        "authorization_id": authorization_id,
        "patient_id": patient_id,
        "provider_id": provider["provider_id"],
        "coverage_id": coverage["coverage_id"],
        "procedure_id": procedure["procedure_id"],
        "diagnosis_id": diagnosis["diagnosis_id"],
        "created_at": format_datetime(created_at),
        "submitted_at": format_datetime(submitted_at),
        "urgency": urgency,
        "initial_submission_complete": int(
            initial_submission_complete
        ),
        "documentation_status": documentation_status,
        "current_status": final_status,
        "decision_at": format_datetime(decision_at),
        "authorization_number": authorization_number,
        "denial_reason": denial_reason,
        "requested_service_date": format_date(
            requested_service_date
        )
    })


# ------------------------------------------------------------
# Write the eight CSV files
# ------------------------------------------------------------

write_csv(
    "patients.csv",
    [
        "patient_id",
        "medical_record_number",
        "first_name",
        "last_name",
        "birth_date",
        "administrative_sex",
        "postal_code"
    ],
    patients
)

write_csv(
    "providers.csv",
    [
        "provider_id",
        "npi",
        "provider_name",
        "specialty",
        "organization_name",
        "active"
    ],
    providers
)

write_csv(
    "payers.csv",
    [
        "payer_id",
        "payer_name",
        "plan_type",
        "standard_sla_hours",
        "expedited_sla_hours",
        "active"
    ],
    payers
)

write_csv(
    "coverages.csv",
    [
        "coverage_id",
        "patient_id",
        "payer_id",
        "member_id",
        "group_number",
        "coverage_start_date",
        "coverage_end_date",
        "coverage_status"
    ],
    coverages
)

write_csv(
    "procedures.csv",
    [
        "procedure_id",
        "procedure_code",
        "procedure_description",
        "service_category",
        "authorization_required"
    ],
    procedures
)

write_csv(
    "diagnoses.csv",
    [
        "diagnosis_id",
        "diagnosis_code",
        "diagnosis_description",
        "code_system"
    ],
    diagnoses
)

write_csv(
    "authorization_requests.csv",
    [
        "authorization_id",
        "patient_id",
        "provider_id",
        "coverage_id",
        "procedure_id",
        "diagnosis_id",
        "created_at",
        "submitted_at",
        "urgency",
        "initial_submission_complete",
        "documentation_status",
        "current_status",
        "decision_at",
        "authorization_number",
        "denial_reason",
        "requested_service_date"
    ],
    authorization_requests
)

write_csv(
    "status_history.csv",
    [
        "status_event_id",
        "authorization_id",
        "status",
        "status_at",
        "actor_type",
        "action_required",
        "event_notes"
    ],
    status_history
)

print()
print("Synthetic data generation completed successfully.")
print(f"Output directory: {OUTPUT_DIRECTORY}")